"""initial_schema

Revision ID: 6ec1034a6d5a
Revises: 
Create Date: 2026-05-01 14:21:25.252877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ec1034a6d5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('careers_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ats_type', sa.Enum('greenhouse', 'lever', 'ashby', 'workday', 'none', 'unknown', name='atstype'), nullable=False),
    sa.Column('ats_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mca_cin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mca_cin_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mca_cin_verified_at', sa.DateTime(), nullable=True),
    sa.Column('gstin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gstin_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gstin_verified_at', sa.DateTime(), nullable=True),
    sa.Column('gstin_trade_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('startup_india_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain_age_days', sa.Integer(), nullable=True),
    sa.Column('whois_creation_date', sa.Date(), nullable=True),
    sa.Column('whois_provider_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('whois_checked_at', sa.DateTime(), nullable=True),
    sa.Column('company_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Enum('draft', 'pending', 'needs_review', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('verification_confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_signals', sa.Integer(), nullable=False),
    sa.Column('reputation_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('has_payment_demand', sa.Boolean(), nullable=False),
    sa.Column('payment_demand_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('sources',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('api', 'html', 'browser', 'manual', name='sourcetype'), nullable=False),
    sa.Column('policy_status', sa.Enum('approved', 'pending', 'blocked', name='policystatus'), nullable=False),
    sa.Column('activation_state', sa.Enum('enabled', 'conditional', 'disabled', name='activationstate'), nullable=False),
    sa.Column('parser_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crawl_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crawl_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('robots_txt_cached', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('robots_txt_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_crawl_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_crawls', sa.Integer(), nullable=False),
    sa.Column('total_parsed', sa.Integer(), nullable=False),
    sa.Column('total_published', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('college_email_domains',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('college_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('company_verifications',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('trust_score_before', sa.Integer(), nullable=True),
    sa.Column('trust_score_after', sa.Integer(), nullable=True),
    sa.Column('risk_score_before', sa.Integer(), nullable=True),
    sa.Column('risk_score_after', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('consent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', 'partial', name='crawlstatus'), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('trigger_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('cards_parsed', sa.Integer(), nullable=False),
    sa.Column('candidates_created', sa.Integer(), nullable=False),
    sa.Column('published_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_source_id'), 'crawl_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('imported_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internships',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('stipend_min', sa.Float(), nullable=True),
    sa.Column('stipend_max', sa.Float(), nullable=True),
    sa.Column('stipend_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stipend_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('payment_confidence', sa.Integer(), nullable=False),
    sa.Column('work_mode', sa.Enum('remote', 'hybrid', 'onsite', name='workmode'), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('eligibility_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apply_by', sa.Date(), nullable=True),
    sa.Column('registration_start', sa.Date(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('draft', 'pending', 'needs_review', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('admin_approved', sa.Boolean(), nullable=False),
    sa.Column('admin_approved_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('admin_approved_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_primary_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('ingestion_mode', sa.Enum('AUTO_SOURCE', 'MANUAL_FORM', 'BULK_IMPORT', name='ingestionmode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('freshness_bucket', sa.Enum('today', 'yesterday', 'last_2_days', 'this_week', 'older', name='freshnessbucket'), nullable=False),
    sa.Column('is_expiring_soon', sa.Boolean(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('domain_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_primary_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internships_apply_by'), 'internships', ['apply_by'], unique=False)
    op.create_index(op.f('ix_internships_city'), 'internships', ['city'], unique=False)
    op.create_index(op.f('ix_internships_company_id'), 'internships', ['company_id'], unique=False)
    op.create_index(op.f('ix_internships_domain_slug'), 'internships', ['domain_slug'], unique=False)
    op.create_index(op.f('ix_internships_freshness_bucket'), 'internships', ['freshness_bucket'], unique=False)
    op.create_index(op.f('ix_internships_is_active'), 'internships', ['is_active'], unique=False)
    op.create_index(op.f('ix_internships_is_paid'), 'internships', ['is_paid'], unique=False)
    op.create_index(op.f('ix_internships_is_public'), 'internships', ['is_public'], unique=False)
    op.create_index(op.f('ix_internships_posted_at'), 'internships', ['posted_at'], unique=False)
    op.create_index(op.f('ix_internships_slug'), 'internships', ['slug'], unique=True)
    op.create_index(op.f('ix_internships_state'), 'internships', ['state'], unique=False)
    op.create_index(op.f('ix_internships_title'), 'internships', ['title'], unique=False)
    op.create_index(op.f('ix_internships_trust_score'), 'internships', ['trust_score'], unique=False)
    op.create_index(op.f('ix_internships_verification_status'), 'internships', ['verification_status'], unique=False)
    op.create_index(op.f('ix_internships_work_mode'), 'internships', ['work_mode'], unique=False)
    op.create_table('source_policies',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('allow_html_scrape', sa.Boolean(), nullable=False),
    sa.Column('allow_api_call', sa.Boolean(), nullable=False),
    sa.Column('allow_browser', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_rph', sa.Integer(), nullable=False),
    sa.Column('respect_robots', sa.Boolean(), nullable=False),
    sa.Column('user_agent_str', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('user_alert_preferences',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('alert_new_matches', sa.Boolean(), nullable=False),
    sa.Column('alert_expiring_saved', sa.Boolean(), nullable=False),
    sa.Column('alert_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_domains', sa.JSON(), nullable=True),
    sa.Column('alert_regions', sa.JSON(), nullable=True),
    sa.Column('alert_stipend_min', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('college_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dpdp_consent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('crawl_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('crawl_job_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_crawl_job_id'), 'crawl_logs', ['crawl_job_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'valid', 'invalid', 'imported', 'duplicate', name='importrowstatus'), nullable=False),
    sa.Column('internship_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_batch_id'), 'import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_rows_status'), 'import_rows', ['status'], unique=False)
    op.create_table('internship_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('internship_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parser_failures',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('crawl_job_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('failure_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stack_trace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parser_failures_source_id'), 'parser_failures', ['source_id'], unique=False)
    op.create_table('suspicious_reports',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('internship_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('reported_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('report_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicious_reports_internship_id'), 'suspicious_reports', ['internship_id'], unique=False)
    op.create_index(op.f('ix_suspicious_reports_resolved'), 'suspicious_reports', ['resolved'], unique=False)
    op.create_table('user_application_tracker',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('internship_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_application_tracker_user_id'), 'user_application_tracker', ['user_id'], unique=False)
    op.create_table('user_saved_internships',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('internship_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_saved_internships_user_id'), 'user_saved_internships', ['user_id'], unique=False)
    op.create_table('verification_checks',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('verification_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('check_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'failed', 'not_run', 'infra_error', name='checkstatus'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('primary_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('evidence_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['company_verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_checks')
    op.drop_index(op.f('ix_user_saved_internships_user_id'), table_name='user_saved_internships')
    op.drop_table('user_saved_internships')
    op.drop_index(op.f('ix_user_application_tracker_user_id'), table_name='user_application_tracker')
    op.drop_table('user_application_tracker')
    op.drop_index(op.f('ix_suspicious_reports_resolved'), table_name='suspicious_reports')
    op.drop_index(op.f('ix_suspicious_reports_internship_id'), table_name='suspicious_reports')
    op.drop_table('suspicious_reports')
    op.drop_index(op.f('ix_parser_failures_source_id'), table_name='parser_failures')
    op.drop_table('parser_failures')
    op.drop_table('internship_sources')
    op.drop_index(op.f('ix_import_rows_status'), table_name='import_rows')
    op.drop_index(op.f('ix_import_rows_batch_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_crawl_logs_crawl_job_id'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    op.drop_table('user_profiles')
    op.drop_table('user_alert_preferences')
    op.drop_table('source_policies')
    op.drop_index(op.f('ix_internships_work_mode'), table_name='internships')
    op.drop_index(op.f('ix_internships_verification_status'), table_name='internships')
    op.drop_index(op.f('ix_internships_trust_score'), table_name='internships')
    op.drop_index(op.f('ix_internships_title'), table_name='internships')
    op.drop_index(op.f('ix_internships_state'), table_name='internships')
    op.drop_index(op.f('ix_internships_slug'), table_name='internships')
    op.drop_index(op.f('ix_internships_posted_at'), table_name='internships')
    op.drop_index(op.f('ix_internships_is_public'), table_name='internships')
    op.drop_index(op.f('ix_internships_is_paid'), table_name='internships')
    op.drop_index(op.f('ix_internships_is_active'), table_name='internships')
    op.drop_index(op.f('ix_internships_freshness_bucket'), table_name='internships')
    op.drop_index(op.f('ix_internships_domain_slug'), table_name='internships')
    op.drop_index(op.f('ix_internships_company_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_city'), table_name='internships')
    op.drop_index(op.f('ix_internships_apply_by'), table_name='internships')
    op.drop_table('internships')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_source_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_table('consents')
    op.drop_table('company_verifications')
    op.drop_table('college_email_domains')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('colleges')
    # ### end Alembic commands ###
